#ifndef __ALTAIR_TASK_STATES_H__
#define __ALTAIR_TASK_STATES_H__



#define ALTAIR_DISPLAY_TASK_STATE_IDLE              0
#define ALTAIR_DISPLAY_TASK_STATE_SPLASH_SCREEN     1
#define ALTAIR_DISPLAY_TASK_STATE_IMU_CALIB         2
#define ALTAIR_DISPLAY_TASK_STATE_IMU_CALIB_FOUND   3
#define ALTAIR_DISPLAY_TASK_STATE_IMU_CALIB_SUCCESS 4
#define ALTAIR_DISPLAY_TASK_STATE_MAIN_MENU         5

#define ALTAIR_DISPLAY_TASK_REQ_NONE                0
#define ALTAIR_DISPLAY_TASK_REQ_IMU_CALIB           1
#define ALTAIR_DISPLAY_TASK_REQ_IMU_CALIB_FOUND     2
#define ALTAIR_DISPLAY_TASK_REQ_IMU_CALIB_SUCCESS   3
#define ALTAIR_DISPLAY_TASK_REQ_CURSOR_INC          4
#define ALTAIR_DISPLAY_TASK_REQ_CURSOR_DEC          5
#define ALTAIR_DISPLAY_TASK_REQ_ENTER               6
#define ALTAIR_DISPLAY_TASK_REQ_BACK                7



#define ALTAIR_BUTTON_TASK_STATE_IDLE     0
#define ALTAIR_BUTTON_TASK_STATE_DEACTIVE 1
#define ALTAIR_BUTTON_TASK_STATE_ACTIVE   2

#define ALTAIR_BUTTON_TASK_REQ_NONE       0
#define ALTAIR_BUTTON_TASK_REQ_ACTIVATE   1
#define ALTAIR_BUTTON_TASK_REQ_DEACTIVATE 2



#define ALTAIR_IMU_TASK_STATE_IDLE        0
#define ALTAIR_IMU_TASK_STATE_INIT_CALIB  1
#define ALTAIR_IMU_TASK_STATE_LIGHT_CALIB 2
#define ALTAIR_IMU_TASK_STATE_READ        3

#define ALTAIR_IMU_TASK_REQ_NONE          0
#define ALTAIR_IMU_TASK_REQ_CHECK_CALIB   1
#define ALTAIR_IMU_TASK_REQ_READ          2

#endif